# Generated by Django 4.2.13 on 2024-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
