# Generated by Django 4.2.13 on 2024-07-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_issue_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
